# Generated by Django 3.0.3 on 2020-07-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date_sent',
            new_name='message_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='new',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
