# Generated by Django 3.0.3 on 2020-07-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
