# Generated by Django 3.0.3 on 2020-07-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200709_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='gallery',
            field=models.ImageField(blank=True, help_text='Select all images at once', null=True, upload_to='listings_upld/gallery'),
        ),
    ]
