# Generated by Django 3.0.3 on 2020-07-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200709_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='gallery',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Select all images at once', null=True, upload_to='listings_upld/gallery')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.Listing')),
            ],
        ),
    ]
