# Generated by Django 3.0.3 on 2020-07-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200709_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
