# Generated by Django 3.0.3 on 2020-07-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_delete_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
