# Generated by Django 3.0.3 on 2020-07-09 12:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0006_delete_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, unique=True)),
                ('category', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold')], max_length=100, null=True)),
                ('type', models.CharField(choices=[('townhomes', 'Townhomes'), ('offices', 'Offices'), ('single_family', 'Single Family'), ('multi_family', 'Multi Family')], max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, null=True)),
                ('status', models.CharField(default='active', max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('featured_image', models.ImageField(null=True, upload_to='listings_upld/featured_image')),
                ('bedrooms', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('bathrooms', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('garage', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True)),
                ('area_size', models.CharField(blank=True, max_length=100, null=True)),
                ('published_on', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Select all images at once', null=True, upload_to='listings_upld/gallery')),
                ('propert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.Property')),
            ],
        ),
    ]
