# Generated by Django 3.0.3 on 2020-07-11 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0008_contactowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactowner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contactowner',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactowner',
            name='date_sent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactowner',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contactowner',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactowner',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
