# Generated by Django 3.0.3 on 2020-07-11 19:15

import ckeditor.fields
from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20200711_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Property Address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area Size (sq ft)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='No. Bathrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='No. Bedrooms'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold')], max_length=100, null=True, verbose_name='Property Category'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=200, null=True, verbose_name='Property City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, unique=True, verbose_name='Property Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='listings_upld/featured_image', verbose_name='Property Feature Image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Property Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(default='active', max_length=200, null=True, verbose_name='Proprty Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('townhomes', 'Townhomes'), ('offices', 'Offices'), ('single_family', 'Single Family'), ('multi_family', 'Multi Family')], max_length=100, null=True, verbose_name='Property Type'),
        ),
    ]
