# Generated by Django 3.0.3 on 2020-07-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_auto_20200711_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='geolocation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
