# Generated by Django 3.0.3 on 2020-07-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20200713_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='propert',
            new_name='property',
        ),
    ]
